### ISSUE TITLE
[Bug Report] Material cards aren't sorted by date of adding

### ISSUE THREAD

**Issue by Anastasiia-Zaikina** [ita-social-projects/dokazovi-requirements#146]
**Environment:** Windows 10x64, Google Chrome v. 92.0.4515.107
**Reproducible:** Always
**Build found:** be: v0.0.9
fe: 58

**Resolution:** Fixed; Dublicate; Cannot reproduce; Not a bug; Not fixable; No change required; Unresolved; Suspended; Won`t fix.

**Preconditions**
Open web application

**Steps to reproduce**
1. Open the "Матеріали" tab
2. Pay attention to the date of adding on material cards

**Actual result**
Material cards aren't sorted by date of adding

**Expected result**
Material cards are sorted by date of adding

**Additional Information** 

**Links**
[Test case #49](https://github.com/ita-social-projects/dokazovi-requirements/issues/49)
[User story #196](https://github.com/ita-social-projects/dokazovi-be/issues/196)

**Attachments**
![Screenshot_232](https://user-images.githubusercontent.com/86487185/127768299-4f022e36-cbd3-44f4-9dae-5af8a448647b.png)

**Comment by Anastasiia-Zaikina** [comment]
Steps to reproduce
1. Open the "Матеріали" tab
2. Click on the "Показати ще 12 матеріалів" button
3. Scroll to the end of page
4. Pay attention to the date of adding
![Screenshot_248](https://user-images.githubusercontent.com/86487185/129685416-3b157f85-d590-49aa-a060-954fb04da070.png)

**Comment by VitaliiKulinskyi** [comment]
!!! question for UNICEF about the length of cards !!!
