### ISSUE TITLE
[Bug Report] Admin control panel: 'Статус' column is empty.

### ISSUE THREAD

**Issue by NatalyaZadorina** [ita-social-projects/dokazovi-requirements#399]
**Environment:** macOS Catalina 10.15.7, Chrome browser, Version 96.0.4664.55, (x86_64)
**Reproducible:** always.
**Build found:** last commit from https://github.com/ita-social-projects/dokazovi-fe

**Resolution:**

**Preconditions**
Administrator is logged in.

**Steps to reproduce**
1. Click the 'Profile icon'.
2. Click 'Особистий кабінет' item in dropdown menu.
3. Click 'Матеріали' item in the left part of the page.

**Actual result**
'Статус' column is empty.

**Expected result**
Each field of 'Статус' column consists of one of the next statuses: 'Опубліковано', 'Заплановано', 'На модерації', 'Потребує редагування'.

**Links**
[Test case #351](https://github.com/ita-social-projects/dokazovi-requirements/issues/351)
[User story #328](https://github.com/ita-social-projects/dokazovi-requirements/issues/328)
[Mock-up](https://www.figma.com/proto/dYtX5TWgBjXIFMG8gWx3x0/Untitled?node-id=30%3A3&amp%3Bscaling=scale-down&amp%3Bpage-id=0%253A1)

**Attachments**
<img width="1033" alt="Снимок экрана 2021-11-18 в 21 04 08" src="https://user-images.githubusercontent.com/92864759/142487083-8a0cea6e-6f5d-4b76-babd-31d749a91e77.png">

**Comment by TkachukI1** [comment]
![image](https://user-images.githubusercontent.com/90401085/148581781-d72aea57-04c3-4a79-9d1c-e6785960317d.png)
