### ISSUE TITLE
[Bug Report] 'Важливе' page: Pop up does not appear after clicking 'Delete'  button

### ISSUE THREAD

**Issue by OlhaOvadovych** [ita-social-projects/dokazovi-requirements#402]
**Environment:** Windows 10 Pro, 64- bit, Google Chrome, Версия 95.0.4638.69.
**Reproducible:** always
**Build found:** [last commit from https://github.com/ita-social-projects/dokazovi-requirements](https://github.com/ita-social-projects/dokazovi-fe)
**Severity:** Minor

**Resolution:** 

**Preconditions**
Administrator is logged in.
"Важливе" page is open
There is at least one card in the Carousel

**Steps to reproduce**
1. Click 'Delete' button on any existing card

**Actual result**
Pop up does not appear with "Ви дійсно хочете видалити цей матеріал з Важливих?" text and with 'Так'/'Ні' buttons after clicking 'Delete' button

**Expected result**
Pop up appears with "Ви дійсно хочете видалити цей матеріал з Важливих?" text and with 'Так'/'Ні' buttons after clicking 'Delete' button

**Links**
[Test case #386](https://github.com/ita-social-projects/dokazovi-requirements/issues?q=is%3Aopen+is%3Aissue+label%3A%22test+case%22)
[User story #264](https://github.com/ita-social-projects/dokazovi-requirements/issues/386)

**Comment by NataHolembiovska** [comment]
Повідомлення з'являється, але назви кнопок не відповідають вимозі https://github.com/ita-social-projects/dokazovi-requirements/issues/386, провели тестування у двох браузер. Скрін прикріпляємо
![Message_US264](https://user-images.githubusercontent.com/99169057/156162556-318b6045-c5c8-4020-a360-423691bce376.jpg)
