### ISSUE TITLE
[Bug Report] 'Додати матерiали' accordion: 'X' icon on 'Переклад' item in 'За типом' filter deletes 'Допис' item

### ISSUE THREAD

**Issue by DashNo** [ita-social-projects/dokazovi-requirements#404]
**Environment:** Windows 10, Google Chrome, 95.0.4638.69 
**Reproducible:** always
**Build found:** last commit from https://github.com/ita-social-projects/dokazovi-fe
**Resolution:** 

**Preconditions**
Administrator is logged in
'Важливе' page is opened

**Steps to reproduce**
1. Click 'Додати матерiали' accordion
2. Click 'За типом' filter
3. Choose 'Переклад' item from multiselect dropdown menu in 'За типом' filter
4. Choose 'Допис' item from multiselect dropdown menu in 'За типом' filter
5. Click 'X' icon on already chosen 'Переклад' item

**Actual result**
1. 'Переклад' item is not deleted from list of already chosen items 
2. 'Допис' item is deleted from list of already chosen items

**Expected result**
1. 'Переклад' item is deleted from list of already chosen items
2. 'Допис' item is not deleted from list of already chosen items

**Additional Information** 

**Links**
[Test case #403](https://github.com/ita-social-projects/dokazovi-requirements/issues/403)
[User story #334](https://github.com/ita-social-projects/dokazovi-requirements/issues/334)

**Attachments**
https://user-images.githubusercontent.com/92861034/142608159-c1e5d162-2e97-41af-b4f7-74d9995d8f79.mp4

**Comment by besizzo** [comment]
Не удается воспроизвести баг: "переклад" и "допис" в разных дропдаун меню, удаляются корректно

**Comment by NataHolembiovska** [comment]
The 'Переклад' item is absent in the 'За типом' filter.  The 'За типом' filter shoud contain 'Стаття', 'Вiдео', 'Допис', 'Переклад' items
![Додати матеріали](https://user-images.githubusercontent.com/99169057/156323090-de92eb63-4a1c-4982-b75e-424be12c4a57.jpg)

**Comment by NataHolembiovska** [comment]
The 'Переклад' item is not shown in the dropdown list of  the 'За типом' filter.  
Bug: When user selected 'Переклад' items in the dropdown list of the 'За типом' filter he/she couldn't cancel this filter.

**Comment by besizzo** [comment]
We only have 3 types for materials: article, video and note

Translation (i.e. Переклад) exists in Origins tab. Please, refer to BA team to adjust the requirements

**Comment by NataHolembiovska** [comment]
Thanks)
