### ISSUE TITLE
[Bug Report] 'Conditions and Contacts' page: Email is not a link in 'Контакти' section 

### ISSUE THREAD

**Issue by IrynaPidberezna** [ita-social-projects/dokazovi-requirements#407]
**Environment:** OS Windows 10, Google Chrome 96.0.4664.45 (x64)
**Reproducible:** always
**Build found:** last commit from https://github.com/ita-social-projects/dokazovi-fe

**Resolution:** 

**Steps to reproduce**
1. Open the site https://dokazovi-frontend.herokuapp.com/
2. Click the 'Контакти' button on the footer of the main page

**Actual result**
Email is not a link in 'Контакти' section of the 'Condition and Contacts' page

**Expected result**
Email is displayed as a link in 'Контакти' section of the 'Condition and Contacts' page. 

**Links**
[Test case #117](https://github.com/ita-social-projects/dokazovi-requirements/issues/117)
[User story #208](https://github.com/ita-social-projects/dokazovi-be/issues/208)
[Mock-up](https://www.figma.com/file/oxKazHLUvWYHjEvSjdcMH3/Dokazovi-5?node-id=2307%3A854)

**Attachments**
![Contacts](https://user-images.githubusercontent.com/92860724/142779996-48b3cd12-94f2-458e-b205-0856581782d8.png)

**Comment by NataHolembiovska** [comment]
The email is not link https://github.com/ita-social-projects/dokazovi-fe/pull/697, but the pointer is displayed while hovering over it.
![Email_US208](https://user-images.githubusercontent.com/99169057/156172197-b23ab9b8-a56d-470b-89d3-1e020435a386.jpg)
