### ISSUE TITLE
[Test for Story #11] Check  "Important" section presence on Main Page

### ISSUE THREAD

**Issue by nmozghova** [ita-social-projects/dokazovi-requirements#5]
**US:** [#11](https://github.com/ita-social-projects/dokazovi-be/issues/11)

**Summary**
On the Main Page the "Important" ("Важливе") section as a slider exist and contain the material cards.

**Preconditions**

Pictures, data about experts and materials has been uploaded and connected to each other in DB.

**Steps**

- [ ] While on Main Page check the existance of "Important" ("Важливе") section
- [ ] Check whether the slider contain material cards
- [ ] Check the material card content
- - [ ] Author's picture
- - [ ] First name, last name
- - [ ] Primary place of work
- - [ ] Material type (article, note, video, course etc.)
- - [ ] Topic
- - [ ] Title
- [ ] Verify the information about materials and experts  corresponds to data in DB
- [ ] Check the presence of "<", ">" buttons and whether they are clickable
- - [ ] Check that click on ">" button change material card to the next in list
- - [ ] While on 1st list check that click on "<" button moves to the last list

**Comment by y-udov** [comment]
Version: 0.0.1
**US:** [#11](https://github.com/ita-social-projects/dokazovi-be/issues/11)

**Summary**
On the Main Page the "Important" ("Важливе") section as a slider exist and contain the material cards.

**Preconditions**

Pictures, data about experts and materials has been uploaded and connected to each other in DB.

**Steps**

- [x] While on Main Page check the existance of "Important" ("Важливе") section
- [ ] Check whether the slider contain material cards  [**Bug**](https://github.com/ita-social-projects/dokazovi-be/issues/146)
- [ ] Check the material card content
- - [ ] Author's picture
- - [ ] First name, last name
- - [ ] Primary place of work
- - [ ] Material type (article, note, video, course etc.)
- - [ ] Topic
- - [ ] Title
- [ ] Verify the information about materials and experts  corresponds to data in DB
- [ ] Check the presence of "<", ">" buttons and whether they are clickable
- - [ ] Check that click on ">" button change material card to the next in list
- - [ ] While on 1st list check that click on "<" button moves to the last list

**Comment by nmozghova** [comment]
**Execution №: 1**
**Version:** N/A

**Steps**

- [ ] While on Main Page check the existance of "Important" ("Важливе") section
- [ ] Check whether the slider contain material cards
- [ ] Check the material card content
- - [ ] Author's picture
- - [ ] First name, last name
- - [ ] Primary place of work
- - [ ] Material type (article, note, video, course etc.)
- - [ ] Topic
- - [ ] Title
- [ ] Verify the information about materials and experts  corresponds to data in DB
- [ ] Check the presence of "<", ">" buttons and whether they are clickable
- - [ ] Check that click on ">" button change material card to the next in list
- - [ ] While on 1st list check that click on "<" button moves to the last list
