### ISSUE TITLE
[Bug Report] Content is not present on "Адміністрування" page

### ISSUE THREAD

**Issue by alexse-oss** [ita-social-projects/dokazovi-requirements#508]
**Environment:** Windows 10 64x, Google Chrome 98.0.4758.102.
**Reproducible:** Always.
**Build found:** [last commit from https://github.com/ita-social-projects/GreenCityClient/tree/dev
E.g. "commit 147fa44"](https://github.com/ita-social-projects/dokazovi-fe)

**Resolution:** Unresolved.

**Preconditions**
User is logged in as an Admin.

**Steps to reproduce**
1. Go to the "Адміністрування" page

**Actual result**
Content is not present on "Адміністрування" page (present on "Особистий кабінет/матеріали" page)

**Expected result**
Content is present on "Адміністрування" page

**Additional Information** 

**Links**
[Test case #497 ](https://github.com/ita-social-projects/dokazovi-requirements/issues/497)
[Test case #451 ](https://github.com/ita-social-projects/dokazovi-requirements/issues/451)
[User story #382 ](https://github.com/ita-social-projects/dokazovi-requirements/issues/382)
[User story #379 ](https://github.com/ita-social-projects/dokazovi-requirements/issues/379)

**Attachments**
https://user-images.githubusercontent.com/83502548/156580509-7043428c-b226-4e81-8be9-bcea35d43466.mp4

**Comment by besizzo** [comment]
![Screenshot at Mar 04 5-16-39 PM](https://user-images.githubusercontent.com/17437295/156789518-4e7c2686-2dd9-4315-83a7-27831b52e1f3.png)

Я так понимаю вам нужны эти статьи?

**Comment by alexse-oss** [comment]
Не зовсім. Потрібні але не в такому виді. Має бути такий вигляд сторінки,
як на мокапі
https://www.figma.com/file/NcyVnGAJypK3az6mFFrGhR/%D0%BD%D0%B0-%D0%BC%D0%BE%D0%B4%D0%B5%D1%80%D0%B0%D1%86%D1%96%D1%97?node-id=0%3A1


пт, 4 бер. 2022 р. о 17:17 besizzo ***@***.***> пише:

**Comment by besizzo** [comment]
> Не зовсім. Потрібні але не в такому виді. Має бути такий вигляд сторінки, як на мокапі https://www.figma.com/file/NcyVnGAJypK3az6mFFrGhR/%D0%BD%D0%B0-%D0%BC%D0%BE%D0%B4%D0%B5%D1%80%D0%B0%D1%86%D1%96%D1%97?node-id=0%3A1 пт, 4 бер. 2022 р. о 17:17 besizzo ***@***.***> пише:
> […](#)

В таком виде (таблица) они в личном кабинете. Для чего дублировать эти статьи в таком же виде?

**Comment by alexse-oss** [comment]
Згідно вимог, ця таблиця має знаходитись тут, а не в особистому кабінеті
Не потрібно дублювати, вона повинна переміститись в адміністрування
ВА так казали

**Comment by besizzo** [comment]
Понял, спасибо
