### ISSUE TITLE
[Bug Report] 'Матеріали' page: Dates of publications with the same title aren’t sorted from newest to oldest in the ‘Дата зміни статусу’ after sorting the title in ascending order

### ISSUE THREAD

**Issue by NataHolembiovska** [ita-social-projects/dokazovi-requirements#509]
**Environment:** Windows 8×64, Firefox 97.0.1, Google Chrome 98.0.4758.102
**Reproducible:** always
**Build found:** last commit from https://github.com/ita-social-projects/dokazovi-requirements

**Resolution:** Unresolved

**Preconditions**
Admin is logged in
'Матеріали' page is opened

**Steps to reproduce**
1. Click the first time on the ‘Заголовок’ title 
2. Go to page 2
3. Pay attention to the order of date in the ‘Дата зміни статусу’ column for publications with the same title

**Actual result**
Dates of publications with the same title aren’t sorted from newest to oldest in the ‘Дата зміни статусу’ after sorting the title in ascending order

**Expected result**
Dates of publications with the same title are sorted from newest to oldest in the ‘Дата зміни статусу’ after sorting the title in ascending order

**Additional Information** 
The bug is appeared in both browsers

**Links**
[Test case #487]( https://github.com/ita-social-projects/dokazovi-requirements/issues/487)
[User story #374](https://github.com/ita-social-projects/dokazovi-requirements/issues/374)

**Attachments**
![Filter_des _US376](https://user-images.githubusercontent.com/99169057/158886942-115de147-f6d4-4e17-801d-0e62d72a4fbf.jpg)

**Comment by mvalchyshen** [comment]
Hello,

Tried to repeat same steps:
1.Click the first time on the ‘Заголовок’ title
2.Pay attention to the order of date in the ‘Дата зміни статусу’ column for publications with the same title

[And got different result. ](https://drive.google.com/file/d/1qyTDOw-1-RpebUOv7mU5MXgf7dA1h6ky/view?usp=sharing)

**Comment by NataHolembiovska** [comment]
Hey. Thanks. I've updated the bug report

**Comment by mvalchyshen** [comment]
But don't close this issue. After checking Bug 510, I'll better assure that it works correctly and will tell you the result On Mon.

**Comment by NataHolembiovska** [comment]
Привіт, так. В мене теж так вже показує) Дякую, але не виконується впорядкування даних на сторінці 2. Я трошки підправлю репортер. Дякую) Надіслано з мого телефону Huawei-------- Оригінальне повідомлення --------Від: mvalchyshen ***@***.***>Дата: чт, 17 бер. 2022 р., 21:35Кому: ita-social-projects/dokazovi-requirements ***@***.***>Копія: NataHolembiovska ***@***.***>, Author ***@***.***>Тема: Re: [ita-social-projects/dokazovi-requirements] [Bug Report] 'Матеріали' page: Dates of publications with the same title aren’t sorted from newest to oldest in the ‘Дата зміни статусу’ after sorting the title in ascending order (Issue #509)

Hello,

Tried to repeat same steps:

1.Click the first time on the ‘Заголовок’ title

2.Pay attention to the order of date in the ‘Дата зміни статусу’ column for publications with the same title

And got different result.
