### ISSUE TITLE
[Bug Report] 'Матеріали' page: Dates of publications with the same title aren’t sorted from newest to oldest in the ‘Дата зміни статусу’ after sorting the title in descending order

### ISSUE THREAD

**Issue by NataHolembiovska** [ita-social-projects/dokazovi-requirements#510]
**Environment:** Windows 8×64, Firefox 97.0.1, Google Chrome 98.0.4758.102
**Reproducible:** always
**Build found:** last commit from https://github.com/ita-social-projects/dokazovi-requirements

**Resolution:** Unresolved

**Preconditions**
Admin is logged in
'Матеріали' page is opened

**Steps to reproduce**
1.	Double-click on the ‘Заголовок’ title
2.	Go to page 2 
3.	Pay attention to the order of date in the ‘Дата зміни статусу’ column for publications with the same title

**Actual result**
Dates of publications with the same title aren’t sorted from newest to oldest in the ‘Дата зміни статусу’ after sorting the title in descending order

**Expected result**
Dates of publications with the same title are sorted from newest to oldest in the ‘Дата зміни статусу’ after sorting the title in descending order

**Additional Information** 
The bug is appeared in both browsers

**Links**
[Test case #487]( https://github.com/ita-social-projects/dokazovi-requirements/issues/487)
[User story #374](https://github.com/ita-social-projects/dokazovi-requirements/issues/374)

**Attachments**
![Descending_US374](https://user-images.githubusercontent.com/99169057/157006523-92a71b6f-7c28-4bdc-85c8-cb3fdc947068.jpg)

**Comment by mvalchyshen** [comment]
Hello,

Issue is understandable, need more time to be fixed.
