### ISSUE TITLE
[Bug Report] 'Матеріали' page: The width of the table and the «Заголовок» field are the inappropriate size in the admin table

### ISSUE THREAD

**Issue by NataHolembiovska** [ita-social-projects/dokazovi-requirements#511]
**Environment:** Windows 8×64, Firefox 97.0.1, Google Chrome 98.0.4758.102
**Reproducible:** always
**Build found:** last commit from https://github.com/ita-social-projects/dokazovi-requirements

**Resolution:** Unresolved

**Preconditions**
The admin is logged in
The admin opened the ‘Materials’ page in his personal account
DevTools => Elements is opened

**Steps to reproduce**
1. Pay attention to the sizes of the table and the «Заголовок» field 

**Actual result**
The width of the table and the «Заголовок» field are smaller sizes in the the admin table

**Expected result**
The width of the «Заголовок» field is 320 pixels and width of the table is at least 1100 pixels in the the admin table

**Additional Information** 
The bug is appeared in both browsers

**Links**
[Test case #504]( https://github.com/ita-social-projects/dokazovi-requirements/issues/504)
[User story #469](https://github.com/ita-social-projects/dokazovi-requirements/issues/469)

**Attachments**
![Size_US469](https://user-images.githubusercontent.com/99169057/157005275-81e90fd1-9de7-4a23-bcb2-36579043af46.jpg)
![Size1_US469](https://user-images.githubusercontent.com/99169057/157005282-c4caae74-03bf-4783-9296-6291e5f5b226.jpg)

**Comment by NataHolembiovska** [comment]
Go to page 2, not all table contents are displayed, the last column is missing. The width of the 'Заголовок' column should be 320 pixels.

**Comment by besizzo** [comment]
We made Title field 320px wide, but table width is a bit bigger than 1100px atm (since content cannot be fitted nicely inside 1100px without any kind of scroll or text overflow)
