### ISSUE TITLE
[Bug Report] The ‘Дата зміни статусу’, ‘Автор’, ‘Заголовок’ filters are not reset on the filter panel after clicking the reset button 

### ISSUE THREAD

**Issue by NataHolembiovska** [ita-social-projects/dokazovi-requirements#526]
**Environment:** Windows 8×64, Firefox 97.0.1, Google Chrome 98.0.4758.102
**Reproducible:** always
**Build found:**  https://github.com/ita-social-projects/dokazovi-requirements

**Resolution:** Unresolved

**Preconditions**
Admin is logged in
Admin has entered a Material page

**Steps to reproduce**
1.	Go to the filter panel
2.	Use the ‘Дата зміни статусу’, ‘Автор’, ‘Заголовок’ filters
3.	Click on the reset button
4.	Pay attention to the filters

**Actual result**
The ‘Дата зміни статусу’, ‘Автор’, ‘Заголовок’ filters are not reset on the filter panel after clicking the reset button

**Expected result**
All filters are reset on the filter panel  after clicking the reset button

**Additional Information** 
The bug is appeared in both browsers

**Links**
[Test case #365]( https://github.com/ita-social-projects/dokazovi-requirements/issues/365)
[User story #333]( https://github.com/ita-social-projects/dokazovi-requirements/issues/333)

**Attachments**

https://user-images.githubusercontent.com/99169057/158760141-c3dd98db-67a9-4cb6-8efd-ec11a50692f8.mp4

**Comment by NataliiaMaistruk** [comment]
The date format on the filter panel needs to be adjusted. 
![date format](https://user-images.githubusercontent.com/99168794/162991403-c172d8e1-a658-4b24-b943-d7b6928e3f21.png)

**Comment by besizzo** [comment]
bug report describes issue with 'clear all filters' button, seems like it's fixed now

We need to make another bug report regarding date format change, and if I'm not mistaken, it already exists
