### ISSUE TITLE
[Bug Report] ‘Керування матеріалами’ page: The dropdown list is contained grammatical mistakes in the ‘Типи’ filter 

### ISSUE THREAD

**Issue by NataHolembiovska** [ita-social-projects/dokazovi-requirements#559]
**Environment:** Windows 8×64, Firefox 97.0.1, Google Chrome 98.0.4758.102
**Reproducible:** always
**Build found:**  https://github.com/ita-social-projects/dokazovi-requirements

**Resolution:** Unresolved

**Preconditions**
User is logged in as an Admin
Admin has entered a ‘Керування матеріалами’ page

**Steps to reproduce**
1.	Go to the admin filters panel
2.	Click on the ‘Типи’ filter 
3.	Look at the spelling of the items 

**Actual result**
Grammatical mistakes are contained in the dropdown list of the ‘Типи’ filter

**Expected result**
The ‘Всі’, ’Статті’, ’Дописи’, ’Відео’ list is shown in the dropdown menu after clicking the ‘Типи’ filter

**Additional Information** 
The ’Допис’ item of ‘за типом’ filter on the ‘Матеріали’ page should be corrected on the ’Дописи’
The bug is displayed in both browsers

**Links**
[Test case #363]( https://github.com/ita-social-projects/dokazovi-requirements/issues/363)
[User story #334]( https://github.com/ita-social-projects/dokazovi-requirements/issues/334)

**Attachments**
![List_Типи_admin_panel](https://user-images.githubusercontent.com/99169057/163952527-138d39c7-1f8e-42a9-8b3c-420e592e3deb.jpg)
![Mockup_Типи](https://user-images.githubusercontent.com/99169057/163952562-4efda6ed-7a0b-4477-8735-8327bed4df94.jpg)

**Comment by besizzo** [comment]
I didn't change spelling on admin page. We're getting singulars from api and it seems like an appropriate way. We could ask BE team to change it, but it might break filters (cannot stay for sure)

Please, talk to BA team and find out whether this is crucial

**Comment by NataHolembiovska** [comment]
BA decided to leave unchanged and close the bug. Thanks
