### ISSUE TITLE
[Bug Report] [Mobile] ‘Матеріали’ page: The ‘Up’ button is shown in orange

### ISSUE THREAD

**Issue by NataHolembiovska** [ita-social-projects/dokazovi-requirements#564]
**Environment:** Honor 10, Android 10, Google Chrome 98.0.4758.102
**Reproducible:** always
**Build found:** https://github.com/ita-social-projects/dokazovi-requirements

**Resolution:** Unresolved

**Preconditions**
User is on the site

**Steps to reproduce**
1.	Open the ‘Матеріали’ page
2.	Pay attention to the color of the ‘Up’ button

**Actual result**
The ‘Up’ button is shown in orange

**Expected result**
The The ‘Up’ button is displayed in grey

**Links**
[Test case #458]( https://github.com/ita-social-projects/dokazovi-requirements/issues/458)
[User story #209]( https://github.com/ita-social-projects/dokazovi-requirements/issues/209)

**Attachments**
![US_209_Up](https://user-images.githubusercontent.com/99169057/164644487-790cc733-0d17-4038-b90d-f3ee3c61cb88.jpg)

**Comment by besizzo** [comment]
It used to be grey but we had to change it since the button was not visible on black background 

Please, let someone from BA know, I'm sure it supposed to stay orange

**Comment by NataHolembiovska** [comment]
You're right, let's leave it in orange. Thanks
